#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 17 17:22:38 MST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_alu_behav -key {Behavioral:sim_2:Functional:tb_alu} -tclbatch tb_alu.tcl -log simulate.log"
xsim tb_alu_behav -key {Behavioral:sim_2:Functional:tb_alu} -tclbatch tb_alu.tcl -log simulate.log

